theme: jekyll-theme-cayman
title: Deon Trevor Mpofu
email: trevordeonmpofu@gmail.com
description: Deon Trevor Mpofu. CEH| ECSA| Phishing Analyst| Cyber Security Analyst| Web Application Penetration Tester| Cyber Threat Hunter| Incident Responder
linkedin_username: deon-trevor-mpofu
twitter_username: DeonMpofu
github_username: Deon-Trevor
gems:
	-jekyll-feed
exclude:
	-Gemfile
	-Gemfile.lock
