
title: My Resume
url: 'https://deon-trevor.github.io'
baseurl: #change it according to your repository name



# Profile information
yourname: Deon Trevor Mpofu 
title: 'Cyber Security Analyst'  
location: Gaborone, Botswana


## Social Profiles
linkedin: https://www.linkedin.com/in/deon-trevor-mpofu
twitter: https://twitter.com/DeonMpofu
facebook: https://www.facebook.com/trevordeon.mpofu



# Update all the sections by editing the files inside _includes folder.
